### ISSUE TITLE
multi planets but no tides in all?

### ISSUE THREAD

**Issue by MilevaE** [marblestation/posidonius#2]
Hi, 

Is it possible to set tides only for some planets, and ignore others, for example in a system where some planets are close-in but others far away from the host star. I guess that this would speed up my simulation..

Thanks!

**Comment by marblestation** [comment]
In the current version of the code in the repository (right now it is not yet a release), it is possible to very easily set what planet you want to "feel" the tides. For instance, the trappist1.py case has:

```
planet_tides = posidonius.effects.tides.OrbitingBody(planet_tides_parameters)
#planet_tides = posidonius.effects.tides.Disabled()
```

If you don't want a particular planet to feel the tides, you would comment the first line and uncomment the second one.

If you have further questions, do not hesitate to drop us an email instead of using github (`sblancocuaresma` at `cfa.harvard.edu` and `emeline.bolmont` at `unige.ch`).

**Comment by MilevaE** [comment]
Thanks!
